openapi: 3.0.3
info:
  title: Losties
  version: "1.0.0"
paths:
  /upload:
    post:
      tags:
        - Utils
      operationId: upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Image successfully uploaded
          content:
            application/json:
              schema:
                type: string
                description: Returns an image file path
  /confirm/{hashcode}:
    post:
      tags:
        - Utils
      operationId: confirmEmail
      parameters:
        - in: path
          name: hashcode
          required: true
          schema:
            type: string
            minimum: 4
          description: The generated hashcode used as path variable
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: Contains entered confirmation code
      responses:
        '200':
          description: Successful confirmation
        '400':
          description: Confirmation fail
  /auth:
    post:
      tags:
        - Utils
      operationId: auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email used as login
                password:
                  type: string
                  description: Password hash
      responses:
        '200':
          description: Successful auth
        '401':
          description: Auth fail

  /owner:
    post:
      tags:
        - Owner
      operationId: addOwner
      requestBody:
        $ref: '#/components/requestBodies/OwnerBody'
      responses:
        '201':
          description: Adds new owner
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Returns owner id
                  location:
                    type: string
                    description: Returns created object location as url
  /owner/{id}:
    get:
      tags:
        - Owner
      operationId: getOwnerById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The owner id used as path variable
      responses:
        '200':
          description: Returns an owner
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'
    delete:
      tags:
        - Owner
      operationId: deleteOwner
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The owner id used as path variable
      responses:
        '204':
          description: Deletes owner
  /owners:
    get:
      tags:
        - Owner
      operationId: getOwners
      description: Gets all owners
      responses:
        '200':
          description: Returns an array of owners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Owner'
  /losty:
    post:
      tags:
        - Losty
      operationId: addLosty
      requestBody:
        $ref: '#/components/requestBodies/LostyBody'
      responses:
        '201':
          description: Adds new losty
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: Returns created object location as url
  /losty/{id}:
    get:
      tags:
        - Losty
      operationId: getLostyById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The losty id used as path variable
      responses:
        '200':
          description: Returns a losty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Losty'
    delete:
      tags:
        - Losty
      operationId: deleteLosty
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The losty id used as path variable
      responses:
        '204':
          description: Deletes losty
  /losties:
    get:
      tags:
        - Losty
      operationId: getLosties
      description: Gets all losties
      responses:
        '200':
          description: Returns an array of losties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Losty'
  /responder:
    post:
      tags:
        - Responder
      operationId: addResponder
      requestBody:
        $ref: '#/components/requestBodies/ResponderBody'
      responses:
        '201':
          description: Adds a responder
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Returns responder id
                  location:
                    type: string
                    description: Returns created object location as url
  /responder/{id}:
    get:
      tags:
        - Responder
      operationId: getResponderById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The responder id used as path variable
      responses:
        '200':
          description: Returns a responder
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Responder'
    delete:
      tags:
        - Responder
      operationId: deleteResponder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The responder id used as path variable
      responses:
        '204':
          description: Deletes responder
  /responders:
    get:
      tags:
        - Responder
      operationId: getResponders
      description: Gets all responders
      responses:
        '200':
          description: Returns an array of responders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Responder'
  /response:
    post:
      tags:
        - Response
      operationId: addResponse
      requestBody:
        $ref: '#/components/requestBodies/LostyBody'
      responses:
        '201':
          description: Adds new Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: Returns created object location as url
  /responses/ad/{id}:
    get:
      tags:
        - Response
      operationId: getResponseByAdId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ad id used as path variable
      responses:
        '200':
          description: Gets all responses by ad id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
    delete:
      tags:
        - Response
      operationId: deleteResponseByAdId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ad id used as path variable
      responses:
        '204':
          description: Deletes response by ad id
  /responses/resp/{id}:
    get:
      tags:
        - Response
      operationId: getResponseByRespId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The responder id used as path variable
      responses:
        '200':
          description: Returns all responses by responder id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
    delete:
      tags:
        - Response
      operationId: deleteResponseByRespId
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The responder id used as path variable
      responses:
        '204':
          description: Deletes response by responder id
  /responses:
    get:
      tags:
        - Response
      operationId: getResponses
      description: Gets all responses
      responses:
        '200':
          description: Returns an array of responses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
  /ad:
    post:
      tags:
        - Ad
      operationId: addAd
      requestBody:
        $ref: '#/components/requestBodies/AdBody'
      responses:
        '201':
          description: Adds new ad
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Returns ad id
                  location:
                    type: string
                    description: Returns created object location as url
  /ad/{id}:
    get:
      tags:
        - Ad
      operationId: getAdById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ad id used as path variable
      responses:
        '200':
          description: Returns an ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
    delete:
      tags:
        - Ad
      operationId: deleteAd
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ad id used as path variable
      responses:
        '204':
          description: Deletes ad
  /ads:
    get:
      tags:
        - Ad
      operationId: getAds
      description: Gets all ads
      responses:
        '200':
          description: Returns an array of ads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ad'
  /payment:
    post:
      tags:
        - Payment
      operationId: addPayment
      requestBody:
        $ref: '#/components/requestBodies/PaymentBody'
      responses:
        '201':
          description: Adds new payment
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                    description: Returns created object location as url
  /payment/{id}:
    get:
      tags:
        - Payment
      operationId: getPaymentById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The payment id used as path variable
      responses:
        '200':
          description: Returns a payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
    delete:
      tags:
        - Payment
      operationId: deletePayment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The payment id used as path variable
      responses:
        '204':
          description: Deletes payment
  /payments:
    get:
      tags:
        - Payment
      operationId: getPayments
      description: Gets all payments
      responses:
        '200':
          description: Returns an array of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'
components:
  requestBodies:
    OwnerBody:
      description: A json object containing owner information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Owner'
    LostyBody:
      description: A json object containing losty information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Losty'
    ResponderBody:
      description: A json object containing responder information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Responder'
    ResponseBody:
      description: A json object containing response information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
    AdBody:
      description: A json object containing ad information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Ad'
    PaymentBody:
      description: A json object containing payment information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Payment'
  schemas:
    Owner:
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        email:
          type: string
    Losty:
      properties:
        id:
          type: integer
        ownerId:
          type: integer
        name:
          type: string
        description:
          type: string
        category:
          type: integer
    Responder:
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        email:
          type: string
    Response:
      properties:
        adsId:
          type: integer
        respId:
          type: integer
        description:
          type: string
    Ad:
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        category:
          type: integer
    Payment:
      properties:
        id:
          type: integer
        adsId:
          type: integer
        isPaid:
          type: boolean
        sum:
          type: integer
        method:
          type: string